# development:
#   cloud_name: "dqaturjpm"
#   api_key: "944614746462417"
#   api_secret: "nhy_Veudz-VWg0TbprLxX-AQclQ"
#   secure: true

# production:
#   cloud_name: "dqaturjpm"
#   api_key: "944614746462417"
#   api_secret: "nhy_Veudz-VWg0TbprLxX-AQclQ"
#   secure: true
